_defaults:
  - "_size_672_maskvd.yml"
dataset:
  name: "waymo"
  split: "val"
  args:
    waymo:
      img_root: "./data/waymo/train/frames"
      ann_files:
        val: "./data/waymo_subset/val/annotations/instances_val.json"
model:
  classes: 3
weights: "results/train/vitdet_waymo_subset_mask/weights_final.pth"
vanilla: true

