_defaults:
  - "_size_672.yml"
dataset:
  name: "waymo"
  train_split: "train"
  val_split: "val"
  args:
    waymo:
      img_root:
        train: "./data/waymo/train/frames"
        val: "./data/waymo/val/frames"
      ann_files:
        train: "./data/waymo_subset/train/annotations/instances_train.json"
        val: "./data/waymo_subset/val/annotations/instances_val.json"
model:
  classes: 3
layerwise_lr_decay:
  enabled: true
  layer_decay: 0.75
  no_weight_decay_list:
    - "position_encoding.encoding"
    - "position_encoding.encoding"
    - "blocks.0.relative_position.y_embedding"
    - "blocks.0.relative_position.x_embedding"
    - "blocks.1.relative_position.y_embedding"
    - "blocks.1.relative_position.x_embedding"
    - "blocks.2.relative_position.y_embedding"
    - "blocks.2.relative_position.x_embedding"
    - "blocks.3.relative_position.y_embedding"
    - "blocks.3.relative_position.x_embedding"
    - "blocks.4.relative_position.y_embedding"
    - "blocks.4.relative_position.x_embedding"
    - "blocks.5.relative_position.y_embedding"
    - "blocks.5.relative_position.x_embedding"
    - "blocks.6.relative_position.y_embedding"
    - "blocks.6.relative_position.x_embedding"
    - "blocks.7.relative_position.y_embedding"
    - "blocks.7.relative_position.x_embedding"
    - "blocks.8.relative_position.y_embedding"
    - "blocks.8.relative_position.x_embedding"
    - "blocks.9.relative_position.y_embedding"
    - "blocks.9.relative_position.x_embedding"
    - "blocks.10.relative_position.y_embedding"
    - "blocks.10.relative_position.x_embedding"
    - "blocks.11.relative_position.y_embedding"
    - "blocks.11.relative_position.x_embedding"