_defaults:
  - "base_672_argoverse.yml"
head_training:
  enabled: false
layerwise_lr_decay:
  enabled: true
  layer_decay: 0.75
  no_weight_decay_list:
    - "position_encoding.encoding"
    - "position_encoding.encoding"
    - "blocks.0.relative_position.y_embedding"
    - "blocks.0.relative_position.x_embedding"
    - "blocks.1.relative_position.y_embedding"
    - "blocks.1.relative_position.x_embedding"
    - "blocks.2.relative_position.y_embedding"
    - "blocks.2.relative_position.x_embedding"
    - "blocks.3.relative_position.y_embedding"
    - "blocks.3.relative_position.x_embedding"
    - "blocks.4.relative_position.y_embedding"
    - "blocks.4.relative_position.x_embedding"
    - "blocks.5.relative_position.y_embedding"
    - "blocks.5.relative_position.x_embedding"
    - "blocks.6.relative_position.y_embedding"
    - "blocks.6.relative_position.x_embedding"
    - "blocks.7.relative_position.y_embedding"
    - "blocks.7.relative_position.x_embedding"
    - "blocks.8.relative_position.y_embedding"
    - "blocks.8.relative_position.x_embedding"
    - "blocks.9.relative_position.y_embedding"
    - "blocks.9.relative_position.x_embedding"
    - "blocks.10.relative_position.y_embedding"
    - "blocks.10.relative_position.x_embedding"
    - "blocks.11.relative_position.y_embedding"
    - "blocks.11.relative_position.x_embedding"

